version: "3"

services:
  bot:
    build:
      context: "."
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - TELEGRAM_TOKEN=t123456789
      - MONGODB_CONNECTION=mongodb123456789
    volumes:
      - .:/codebase
